server:
  port: 8080

spring:
  application:
    name: auth-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}

jwt:
  secret: uma-chave-secreta-super-segura-com-mais-32-bytes # Mude para uma chave diferente e mais longa (min 32 bytes)
  expiration: 3600000 # 1 hora em milissegundos (60 minutos * 60 segundos * 1000 milissegundos)
