server:
  port: 8084 # Porta em que o stock-service será executado

spring:
  application:
    name: stock-service # Nome do serviço, usado no Eureka
  datasource:
    url: jdbc:postgresql://localhost:5432/mercadotech_stock
    username: mercadotech_user # <--- Altere para o usuário correto
    password: senha_segura # <--- Altere para a senha correta
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Estratégia de criação/atualização do schema do banco (pode ser "none", "update", "create", "create-drop")
    show-sql: true # Exibe as queries SQL no console (útil para debug)
    properties:
      hibernate:
        format_sql: true # Formata as queries SQL no console
  config:
    import: "optional:configserver:" # Habilita o Config Server para buscar configurações

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # URL do Eureka Discovery Server
    fetch-registry: true # Busca o registro de serviços do Eureka
    register-with-eureka: true # Registra este serviço no Eureka
  instance:
    hostname: localhost # Nome do host para o registro no Eureka (pode ser ajustado em produção)
    instance-id: ${spring.application.name}:${random.value} # ID único da instância no Eureka

product-service:
  url: http://localhost:8082 # URL base do product-service